name: firsttest
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
      - run: echo "good morning"
      - name: print bye
      - run: echo "bye"
